development:
  adapter: postgresql
  database: zs_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: zs_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: <%= Rails.application.secrets[:database][:name] %>
  pool: 5
  host: <%= Rails.application.secrets[:database][:host] %>
  port: 5432
  username: <%= Rails.application.secrets[:database][:usrname] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  timeout: 5000
