# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

production:
  url: 'postgres://dilussion_3:zPI)(*123:sql.dilussion.nazwa.pl:5432/dilussion_3'
  database:
    :host: 'sql.dilussion.nazwa.pl'
    :name: 'dilussion_3'
    :usrname: 'dilussion_3'
    :password: '123Zpiwsiz'
  secret_key_base: a5ee7afbefb6909c49c15359c72b4230275127d0fb8b2278445706139ae875e5457c6bf1dbeab45844ea9ba3f8bb104a3fe8e229e102643eebe439341d765da8

development:
  database:
    :host: 'sql.dilussion.nazwa.pl'
    :name: 'dilussion_3'
    :usrname: 'dilussion_3'
    :password: '123Zpiwsiz'
  # database:
    # :name: 'zs_development'
  secret_key_base: 57ff73f9f892bdea87b3a4379854ecfe5f586cb1daf5d1469c88c79a788a49cb4d9854b3c1b21e8a2a1e60d3fe53e5d97f2a4306bd94fa164247002ece712ed3

test:
  database:
    :name: 'zs_test'
  secret_key_base: 85c1d2c98e64a7cee27e237729da4073fc72c22d0648b185ec00d73b334e4a2f8ef33c91f4d13e73ee9aa0a31685d7a9a6917be5b20b92c458a9901d6763dbfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
